### ISSUE TITLE
Emojis not rendering consistently across different browsers and systems

### ISSUE THREAD

**Issue by vinay-osseed** [vinugawade/vinux.in#1]
**Description:**
The emojis on the website are not rendering consistently on various browsers and systems. Here is how they appear on different platforms:

- Chrome (macOS):
   ![Home Page - Chrome](https://github.com/vinugawade/vinux.in/assets/89973450/3072abe2-0ebe-4111-9418-b23d541636a0)

- Firefox (macOS):
   ![Home Page - Firefox](https://github.com/vinugawade/vinux.in/assets/89973450/39f0f7e2-fded-44c8-ac83-e305ef9f07b8)

**Steps to Reproduce:**
1. Open the website using Chrome (Latest Version) on macOS.
2. Navigate to the home page :- [vinux.in](https://vinux.in).
3. Observe that certain emojis are not displayed correctly.
4. Repeat the steps using Firefox (Latest Version) on macOS and note the inconsistencies in emoji rendering.

**Expected Behavior:**
The emojis should be consistently displayed across different browsers and systems.

**Additional Information:**
- Browser: Chrome (Latest Version), Firefox (Latest Version) and others
- Operating System: macOS

**Comment by vinugawade** [comment]
Updated emojis on site. Closing the issue.
